### ISSUE TITLE
App not run, after installing package

### ISSUE THREAD

**Issue by Oleksandrrr** [Asaye/react-native-media-recorder#1]
Hi, have a problem, install package, then react-native link, and when run react-native run-android get error :
A problem occurred configuring project ':react-native-media-recorder'.
> Could not resolve all artifacts for configuration ':react-native-media-recorder:classpath'.
   > Could not find com.android.tools.build:gradle:3.3.2.

I use different versions of RN, and error the same

**Comment by Asaye** [comment]
The easiest solution for this problem is to use the same gradle version for both react-native-media-recorder module and for your RN. Just open "yourAppName/android/build.gradle" file and get what version of gradle that you are using for your RN from the "dependencies" closure. Then, open "yourAppName/node_modules/react-native-media-recorder/android/build.gradle" file and change the gradle version in the "dependencies" closure to the same version   as above. Then, save the changes, clean your project and run your app. I hope this will solve the issue. If it doesn't, please let me know.

**Comment by Oleksandrrr** [comment]
I change gradle version in react-native-media-recorder, and  change "/node_modules/react-native-media-recorder/android/build.gradle", and app started successfully,
my changes is:
```
buildscript {
    repositories {
mavenLocal() //removed
        google() // add this line
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2' //change to version of my app 
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 28
    buildToolsVersion "28.0.3"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
    }
    lintOptions {
        abortOnError false
    }
}

repositories {
    mavenCentral()
    mavenLocal() // add here
}

dependencies {
    compile 'com.facebook.react:react-native:+'
}
```
thank you for an answer

**Comment by Asaye** [comment]
That is great. Would you mind if I close this issue?

**Comment by Oleksandrrr** [comment]
Yes, issue is close 👍
